files:
  - source: /public/metadata/licenses/en-US.md
    translation: /%original_path%/%locale%.%file_extension%
  - source: /public/metadata/messages/en-US.json
    translation: /%original_path%/%locale%.%file_extension%
