query CostCenters(
  $id: ID!
  $page: Int
  $pageSize: Int
  $sortOrder: String
  $search: String
  $sortedBy: String
) {
  getCostCentersByOrganizationId(
    id: $id
    search: $search
    page: $page
    pageSize: $pageSize
    sortOrder: $sortOrder
    sortedBy: $sortedBy
  ) @context(provider: "vtex.b2b-organizations-graphql") {
    data {
      id
      name
    }
    pagination {
      page
      pageSize
      total
    }
  }
}
