query Organizations(
  $search: String
  $page: Int
  $pageSize: Int
  $sortOrder: String
  $sortedBy: String
) {
  getOrganizations(
    search: $search
    page: $page
    pageSize: $pageSize
    sortOrder: $sortOrder
    sortedBy: $sortedBy
  ) @context(provider: "vtex.b2b-organizations-graphql") {
    data {
      id
      name
      costCenters
    }
    pagination {
      page
      pageSize
      total
    }
  }
}
