query SearchUsers($perPage: Int!, $pageNumber: Int!, $filter: String) {
  totalNumberOfUsers(filter: $filter)
  users(perPage: $perPage, pageNumber: $pageNumber, filter: $filter) {
    id
    email
    firstName
    lastName
    gender
    userId
    document
    documentType
    birthDate
    corporateName
    isCorporate
    corporateDocument
    corporateName
    phone
    homePhone
    businessPhone
    isNewsletterOptIn
    stateRegistration
  }
}
